# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# First Stage: Build the TypeScript project
FROM node:22.12-alpine AS builder

# Set working directory
WORKDIR /app

# Copy all necessary files for npm install
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies
RUN npm install

# Copy source files
COPY src ./src

# Build the project
RUN npm run build

# Second Stage: Production Image
FROM node:22-alpine AS release

# Set working directory
WORKDIR /app

# Copy built files and package configuration
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package-lock.json /app/

# Install production dependencies
RUN npm ci --omit=dev

# Set environment variables
# (These would typically be configured at runtime, but you can set defaults or example values here)
ENV BOX_JWT_CONFIG_PATH=/path/to/your/box-jwt-config.json
ENV BOX_USER_ID=123456

# Command to run the application
ENTRYPOINT ["node", "dist/index.js"]
